nginx:
    build: ./nginx
    links:
        - fireland:fireland
        - refaction:refaction
    ports:
        - "80:80"
        - "8081:8081"
        
refaction:
    build: ./refaction-vue
    links:
        - redis
        - mongodb
    ports:
        - "3030"
    volumes:
        - ./refaction-vue/:/home/app
        - /home/app/node_modules

fireland:
    build: ./fireland-vue
    links:
        - redis
        - mongodb
    ports:
        - "3030"
    volumes:
        - ./fireland-vue/:/home/app
        - /home/app/node_modules

jenkins:
    build: ./jenkins-docker
    ports:
        - "8090:8080"
        - "50000:50000"
    volumes:
        - "./jenkins:/var/jenkins_home"
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "/usr/bin/docker:/usr/bin/docker"

redis:
    image: redis
    ports:
        - "6379"

mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db/
    
