version: '3'

services:
    nginx:
        build: ./nginx
        links:
            - server1:server1
            - server2:server2
        ports:
            - "80:80"
            - "8081:8081"
            
    server1:
        build: ./node-server
        links:
            - redis
            - mongo
        ports:
            - "3030"
        volumes:
            - ./node-server/:/home/app
            - /home/app/node_modules  

    server2:
        build: ./node-server
        links:
            - redis
            - mongo
        ports:
            - "3030"
        volumes:
            - ./node-server/:/home/app
            - /home/app/node_modules    
     
    redis:
        image: redis
        ports:
            - "6379"

    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27017"
    