nginx:
    build: ./nginx
    links:
        - fireland:fireland
        - refactoring:refactoring
    ports:
        - "80:80"
        - "8081:8081"
        
refactoring:
    build: ./refactoring-home-vue
    links:
        - redis
        - mongo
    ports:
        - "3030"
    volumes:
        - ./refactoring-home-vue/:/home/refactoring
        - /home/refactoring/node_modules

fireland:
    container_name: fireland
    build: ./fireland-vue
    links:
        - redis
        - mongo
    ports:
        - "3030"
    volumes:
        - ./fireland-vue/:/home/app
        - /home/app/node_modules

jenkins:
    build: ./jenkins-docker
    ports:
        - "8090:8080"
        - "50000:50000"
    volumes:
        - "./jenkins:/var/jenkins_home"
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "/usr/bin/docker:/usr/bin/docker"

redis:
    image: redis
    ports:
        - "6379"

mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017"
    volumes:
      - mongo:/data/db/
    
