nginx:
    build: ./nginx
    links:
        - fireland:fireland
    ports:
        - "80:80"
        
fireland:
    build: ./refaction-vue
    links:
        - redis
        - mongodb
    ports:
        - "3030:3030"
    volumes:
        - ./refaction-vue/:/home/app
        - /home/app/node_modules

jenkins:
    build: ./jenkins-docker
    ports:
        - "8090:8080"
        - "50000:50000"
    volumes:
        - "./jenkins:/var/jenkins_home"
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "/usr/bin/docker:/usr/bin/docker"

redis:
    image: redis
    ports:
        - "6379"

mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db/
    
